Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.network "private_network", ip: "192.168.33.10"

    # Aumenta el tiempo de espera a 10 o 15 minutos (600 o 900 segundos)
    config.vm.boot_timeout = 600
    
    # Provisionamiento con Ansible LOCAL (se instala en la VM)
    config.vm.provision "ansible", type: "ansible_local" do |ansible|
        ansible.playbook = "playbook.yml"
        # ansible.inventory_path = "inventories/vagrant/hosts.ini"
        ansible.verbose = "v"
    end
end