- name: Instalar Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copiar página HTML personalizada
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html
    mode: '0644'

- name: Asegurar que Nginx esté corriendo y habilitado
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes